name: Push new tag update to stable branch

on:
  schedule:
    # Daily for now
    - cron: '9 7 * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  update-snapcraft-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Run desktop-snaps action
        uses: snapcrafters/ci/sync-version@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
          update-script: |
            VERSION=$(git -c 'versionsort.suffix=-' ls-remote --refs --sort='v:refname' --tags https://codeberg.org/valos/Komikku.git | tail --lines=1 | cut --delimiter='/' --fields=3)
            yq -i '.parts.komikku.source-tag = \"$VERSION\"' snap/snapcraft.yaml
